### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by sanolilais** [sanolilais/purple-moon-store#3]
**This navigation bar has links to other sections of the site. It will also implement a search box which is a separate component.**

**Comment by sanolilais** [comment]
**Subtasks**

- [ ] Style the site name "Purple Moon Store" according to the style pattern.

- [ ] Style the menu links according to the style pattern.

- [ ] Create search bar with magnifying glass icon.

- [ ] Add favorite icon/button.

- [ ] Add icon/button to cart.
